// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// estep
arma::mat estep(arma::vec y, arma::vec pi, arma::mat mu, arma::mat sigma);
RcppExport SEXP _FMHighLD_estep(SEXP ySEXP, SEXP piSEXP, SEXP muSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type mu(muSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(estep(y, pi, mu, sigma));
    return rcpp_result_gen;
END_RCPP
}
// lmm_comp_var
arma::mat lmm_comp_var(arma::vec var_factors, arma::vec residual_error, arma::vec re_error);
RcppExport SEXP _FMHighLD_lmm_comp_var(SEXP var_factorsSEXP, SEXP residual_errorSEXP, SEXP re_errorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type var_factors(var_factorsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type residual_error(residual_errorSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type re_error(re_errorSEXP);
    rcpp_result_gen = Rcpp::wrap(lmm_comp_var(var_factors, residual_error, re_error));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FMHighLD_estep", (DL_FUNC) &_FMHighLD_estep, 4},
    {"_FMHighLD_lmm_comp_var", (DL_FUNC) &_FMHighLD_lmm_comp_var, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_FMHighLD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
