# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estep <- function(y, pi, mu, sigma) {
    .Call(`_FMHighLD_estep`, y, pi, mu, sigma)
}

lmm_comp_var <- function(var_factors, residual_error, gene_error) {
    .Call(`_FMHighLD_lmm_comp_var`, var_factors, residual_error, gene_error)
}

