# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' E-step
#' 
#' Calculates the E-step probabilities in the implementation
#' of the EM-algorithm for mixture models used by FM-HighLD
#' 
#' @param y a vector with the association statistics with length n
#' @param pi a vector with the prior prob. of allocation into the
#'   components with length k
#' @param mu a nxk matrix with the conditional means of Y | Z = k
#' @param sigma a nxk matrix with the conditional std. dev of Y | Z = k
#' @return a nxk matrix with entries
#'   P(Z_i = k | Y_i = y_i , mu = mu_ik ,sigma = sigma_ik)
#' @export
estep <- function(y, pi, mu, sigma) {
    .Call('_FMHighLD_estep', PACKAGE = 'FMHighLD', y, pi, mu, sigma)
}

#' Computes the variance of a linear mixed model
#'
#' @param var_factors a vector with the variances for each component of
#'   the linear mixed model random effects
#' @param residual_error a vector with the residual errors of the
#'   linear mixed model used by FM-HighLD
#' @param re_error a vector with the random effect erros of the linear
#'   mixed model used by FM-HighLD
#' @return The variance matrix of the model
lmm_comp_var <- function(var_factors, residual_error, re_error) {
    .Call('_FMHighLD_lmm_comp_var', PACKAGE = 'FMHighLD', var_factors, residual_error, re_error)
}

