# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' E-step 
#' 
#' Calculates the E-step probabilities in the implementation
#' of the EM-algorithm for mixture models
#' 
#' @param y a vector with the association statistics with length n
#' @param pi a vector with the prior prob. of allocation into the components with length k
#' @param mu a nxk matrix with the conditional means of Y | Z = k
#' @param sigma a nxk matrix with the conditional std. dev of Y | Z = k
#' @return a nxk matrix with entries P(Z_i = k | Y_i = y_i , mu = mu_ik ,sigma = sigma_ik)
#' @export
estep <- function(y, pi, mu, sigma) {
    .Call(`_FMHighLD_estep`, y, pi, mu, sigma)
}

lmm_comp_var <- function(var_factors, residual_error, gene_error) {
    .Call(`_FMHighLD_lmm_comp_var`, var_factors, residual_error, gene_error)
}

